FROM apache/airflow:latest-python3.9

WORKDIR /opt/airflow/dags
COPY pyproject.toml /opt/airflow/dags

RUN pip3 install poetry --user
RUN poetry install
RUN poetry export -f requirements.txt >> requirements.txt

RUN pip install --user --upgrade pip
RUN pip install --no-cache-dir --user -r requirements.txt

USER root
RUN apt-get update                             \
 && apt-get install -y --no-install-recommends \
    ca-certificates curl firefox-esr           \
 && rm -fr /var/lib/apt/lists/*                \
 && curl -L https://github.com/mozilla/geckodriver/releases/download/v0.33.0/geckodriver-v0.33.0-linux64.tar.gz | tar xz -C /usr/local/bin \
 && apt-get purge -y ca-certificates curl
USER airflow



