FROM python:3.9-slim-bullseye

WORKDIR /app
COPY pyproject.toml /app

RUN apt update -y && apt upgrade -y && apt install curl -y
RUN curl -sSL https://install.python-poetry.org | POETRY_HOME=/opt/poetry python3 -

RUN cd /usr/local/bin && ln -s /opt/poetry/bin/poetry

RUN poetry config virtualenvs.create false 
RUN poetry install

EXPOSE 80
