FROM python:3.9-slim-bullseye

WORKDIR /app
COPY requirements_clustering.txt /app

RUN apt update -y && apt upgrade -y && apt install curl -y && apt-get install -y python-dev python3-pip
RUN pip3 install -r requirements_clustering.txt

EXPOSE 80
